In [1]:
from tensorflow.keras.preprocessing.text import one_hot 

In [2]:
sent=['the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',

]


In [4]:
# define the vocab size
voc_size=10000

In [5]:
# one hot representation for every word

one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[8659, 8232, 8033, 8555],
 [8659, 8232, 8033, 8001],
 [8659, 6674, 8033, 7954],
 [5488, 7179, 673, 8474, 7954],
 [5488, 7179, 673, 8474, 9275],
 [8494, 8659, 8121, 8033, 7191],
 [3696, 8226, 1895, 8474]]

In [7]:
# word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [8]:
import numpy as np


In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)

In [10]:
embedded_docs

array([[   0,    0,    0,    0, 8659, 8232, 8033, 8555],
       [   0,    0,    0,    0, 8659, 8232, 8033, 8001],
       [   0,    0,    0,    0, 8659, 6674, 8033, 7954],
       [   0,    0,    0, 5488, 7179,  673, 8474, 7954],
       [   0,    0,    0, 5488, 7179,  673, 8474, 9275],
       [   0,    0,    0, 8494, 8659, 8121, 8033, 7191],
       [   0,    0,    0,    0, 3696, 8226, 1895, 8474]], dtype=int32)

In [11]:
# feature representation 

dim=10



In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.predict(embedded_docs)

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2026-06-30 17:46:11.614062: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 292ms/step


array([[[-2.92592049e-02,  2.84436829e-02, -4.51237671e-02,
         -9.19083506e-03,  3.49522345e-02,  1.97287090e-02,
          2.87144892e-02, -1.69866160e-03,  4.94850315e-02,
          3.36522572e-02],
        [-2.92592049e-02,  2.84436829e-02, -4.51237671e-02,
         -9.19083506e-03,  3.49522345e-02,  1.97287090e-02,
          2.87144892e-02, -1.69866160e-03,  4.94850315e-02,
          3.36522572e-02],
        [-2.92592049e-02,  2.84436829e-02, -4.51237671e-02,
         -9.19083506e-03,  3.49522345e-02,  1.97287090e-02,
          2.87144892e-02, -1.69866160e-03,  4.94850315e-02,
          3.36522572e-02],
        [-2.92592049e-02,  2.84436829e-02, -4.51237671e-02,
         -9.19083506e-03,  3.49522345e-02,  1.97287090e-02,
          2.87144892e-02, -1.69866160e-03,  4.94850315e-02,
          3.36522572e-02],
        [ 6.05864450e-03,  1.29160620e-02, -2.19962001e-02,
          1.61702745e-02,  5.67317009e-03,  4.24857475e-02,
          1.21724606e-02,  1.43411420e-02,  4.995784

In [18]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 8659, 8232, 8033, 8555], dtype=int32)

In [23]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step


array([[[-0.0292592 ,  0.02844368, -0.04512377, -0.00919084,
          0.03495223,  0.01972871,  0.02871449, -0.00169866,
          0.04948503,  0.03365226],
        [-0.0292592 ,  0.02844368, -0.04512377, -0.00919084,
          0.03495223,  0.01972871,  0.02871449, -0.00169866,
          0.04948503,  0.03365226],
        [-0.0292592 ,  0.02844368, -0.04512377, -0.00919084,
          0.03495223,  0.01972871,  0.02871449, -0.00169866,
          0.04948503,  0.03365226],
        [-0.0292592 ,  0.02844368, -0.04512377, -0.00919084,
          0.03495223,  0.01972871,  0.02871449, -0.00169866,
          0.04948503,  0.03365226],
        [ 0.00605864,  0.01291606, -0.0219962 ,  0.01617027,
          0.00567317,  0.04248575,  0.01217246,  0.01434114,
          0.04995785, -0.02874216],
        [-0.00805495,  0.01444011,  0.04000643,  0.03911419,
          0.03353704,  0.02213066, -0.03739897,  0.03202404,
          0.00841971, -0.0266404 ],
        [ 0.02109443,  0.02543118, -0.03853784,  0.0